name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]   # sua branch é master
  pull_request:
    branches: [ "master" ]

jobs:
  # ================= CI =================
  test:
    name: Rodar testes no Back e Front
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # ----- Backend -----
      - name: Configurar Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências do Backend
        run: |
          cd backend
          npm install
          npm test

      # ----- Frontend -----
      - name: Configurar Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências do Frontend
        run: |
          cd frontend
          npm install
          npm test

  # ================= CD =================
  deploy:
    name: Deploy em Produção
    needs: test   # só roda se os testes passarem
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # ----- Deploy do Backend (Netlify) -----
      - name: Deploy Backend na Netlify
        run: npx netlify deploy --dir=backend --prod --auth=${{ secrets.NETLIFY_AUTH_TOKEN }} --site=${{ secrets.NETLIFY_SITE_ID }}

      # ----- Deploy do Frontend (Vercel) -----
      - name: Deploy Frontend na Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
